Implement forgotten password funcitonality
podkrepi-bg/api pull request #324
Opened 2022-08-09 12:58 UTC by borislavstoychev

## Requested changes from [frontend](https://github.com/podkrepi-bg/frontend/issues/898)
### Used new library for generate JWT [@nestjs/jwt ](https://github.com/nestjs/jwt)
### Not ready yet 
- to do tests

2022-08-12 12:28 UTC, igoychev requested changes

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/auth.service.ts
> +  async forgotPass(forgotPasswordDto: ForgotPass) {
this method should be called sendMailForPasswordChange because this is what it is doing

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/auth.service.ts
> +  async recoveryPass(recoveryPasswordDto: RecoveryPasswordDto) {
this method should be called updateForgottenPassword, because this is what it is used for

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/auth.service.ts
> +    const jtwSecret = process.env.JWT_SECRET_KEY
no need to rename variables, just use them where they are needed directly

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/dto/forgot-password.dto.ts
> +}
this contains the ForgottenPasswordEmail - let's call it by what it contains

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/dto/recovery-password.dto.ts
> +}
naming suggestion - let's call this NewPasswordDto because this is what it contains

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/login.controller.ts
> +  }
let's rename to reset-password, because recovery is not suitable for this activity

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/assets/templates/forgot-password.mjml
> +          Ако не сте пускали подобна заявка, не е необходимо да правите каквото и да е било.<br /><br />
не е необходимо да правите нищо.

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/assets/templates/forgot-password.mjml
> +          Ако Вие сте поискали възстановяване на паролата, избере бутона „Нова парола“.<br /><br />
избере бутона => натиснете бутона

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/assets/templates/forgot-password.json
> +  "subject": "Възстановяване на достъп до Подкрепи.бг"
Забравена парола за Подкрепи.бг

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/email/template.interface.ts
> +export class ForgotPassDto extends EmailTemplate<CreatePersonDto> {
ForgottenPasswordMailDto

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/auth.service.ts
> +        : new BadRequestException('JWT is expired, request new link!')
let's say what happened,  so it is understandable without revealing implementation details: 
"The forgotten password link has expired, request a new link and try again!"

2022-08-12 12:28 UTC, igoychev commented on package.json
> +    "@nestjs/jwt": "^9.0.0",
great choice of nestjs/jwt !

2022-08-12 12:28 UTC, igoychev commented on apps/api/src/auth/auth.module.ts
> +  providers: [AuthService, PrismaService, EmailService, JwtService, TemplateService],
please add these in auth.service.spec.ts , to not break the tests

2022-08-13 08:28 UTC, borislavstoychev commented on apps/api/src/auth/auth.service.ts
> +    const appUrl = this.config.get<string>('APP_URL_LOCAL')
Please check this [commit](https://github.com/podkrepi-bg/api/pull/324/commits/092dcd29a6dbd7ae35b5dd79d44c3580bbaa7a3b), if you have this in mind

2022-08-14 12:32 UTC, igoychev approved these changes
Well done!

2022-08-14 15:58 UTC, merged