Feature/update donation person
podkrepi-bg/api pull request #348
Opened 2022-10-28 07:56 UTC by stann1

the backend part for: https://github.com/podkrepi-bg/frontend/issues/958

2022-10-28 13:27 UTC, igoychev requested changes
great overall, pls check my comments below

2022-10-28 13:50 UTC, stann1 commented on apps/api/src/donations/donations.service.ts
> +        throw new BadRequestException('Succeeded donations cannot be updated.')
this was the original message, and I actually like it - short and to the point

2022-10-28 13:50 UTC, stann1 commented on apps/api/src/donations/donations.service.ts
> +          )
true, but then the user will get a system unhandled exception, this way it is much more user friendly

2022-10-28 13:51 UTC, stann1 commented on apps/api/src/donations/donations.service.ts
>        }
I agree, will change it

2022-11-01 08:25 UTC, igoychev commented on apps/api/src/donations/donations.service.ts
> +          )
What do you think about handling the exception. Just found that Prisma has an error code for this case P2003 and the exception docs show how to handle it: https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors

2022-11-02 13:08 UTC, igoychev approved these changes

2022-11-02 13:19 UTC, merged