Seed more donations for campaigns
podkrepi-bg/api pull request #369
Opened 2022-11-28 15:41 UTC by batebobo

Implements #364 

Added two new campaings:
* One completed with 3 donations
* One active with 25 donations

Also added corresponding vaults for both campaigns

## Screenshots

The two new campaigns in the home page:
<img width="1704" alt="Screenshot 2022-11-28 at 7 58 26 PM" src="https://user-images.githubusercontent.com/6130708/204348100-211ae9aa-7f2c-4f33-9525-9246be10e587.png">

The heavily funded campaign (25 donations):
<img width="1728" alt="Screenshot 2022-11-28 at 7 58 52 PM" src="https://user-images.githubusercontent.com/6130708/204348155-bed454e0-96c3-40d6-bd07-e47254f6e368.png">

2022-11-28 16:09 UTC, kachar approved these changes
I haven't tested it but it looks good to me :raised_hands: Thanks for the contribution @batebobo

2022-11-28 16:17 UTC, kachar commented
@batebobo Please check the API test run

2022-11-28 17:55 UTC, batebobo commented
@kachar Might be because I don't have permissions to the `api` repo (as per [this](https://github.com/actions/first-interaction/issues/10)). All tests are successful, the check only fails on report generation, which according to my search about the error has something to do with permission on `Actions`'s side and the fact that I'm creating the PR from a fork 😕

2022-11-28 17:56 UTC, batebobo commented
I'll also include screenshots of the newly added campaigns and donations and also results from a local test run :v:

2022-11-28 20:17 UTC, kachar commented
@imilchev Might be able to advise on the actions issue here

2022-11-28 20:19 UTC, imilchev commented
We haven't tested our actions with forks. You have found an issue apparently 😛 Can you submit an issue to the repo for this problem? I will try to fix it in the coming days. I know what needs to happen, just need to find some time to implement it

2022-11-28 20:22 UTC, imilchev commented
Once the issue is created I will merge the PR

2022-11-29 09:04 UTC, igoychev requested changes
Great job of seeding the database with the donations and types of campaigns!
Please see my comments, for needed adjustments of amounts and dependencies that you might not have been aware of.

2022-11-29 09:15 UTC, batebobo commented on db/seed/donations.seed.ts
> +        currency: Currency.BGN,
The intention here was to be sure that we would at least reach the target amount, so that the campaign is properly completed

2022-11-29 09:16 UTC, batebobo commented on db/seed/donations.seed.ts
> +        amount: parseInt(faker.finance.amount(100, 1000)),
Not really, now that I think of it it makes more sense for the target to be 250

2022-11-29 09:24 UTC, batebobo commented on db/seed/vault.seed.ts
> +      amount: 10000,
Thanks for both comments about the amount! It seems that the first vault here also does not adhere to this rule. Does it make sense to update it as well?

2022-11-29 09:42 UTC, batebobo commented on db/seed/vault.seed.ts
> +      amount: 10000,
I just reflected this for all vaults and also added some comments. Let me know how it looks :)

2022-11-29 09:50 UTC, batebobo commented
@imilchev Issue about the API tests CI https://github.com/podkrepi-bg/api/issues/370 😬

2022-11-29 20:09 UTC, imilchev commented
@batebobo can you rebase your branch on latest `master`. I think the tests should pass now

2022-11-29 20:10 UTC, imilchev commented
Nevermind, I did it

2022-11-30 16:38 UTC, igoychev approved these changes

2022-11-30 17:29 UTC, merged