Edit campaing application task(Admin and Organaizer)
podkrepi-bg/api pull request #660
Opened 2024-07-25 19:48 UTC by Martbul

2024-07-26 08:24 UTC, slavcho requested changes

2024-07-26 08:24 UTC, slavcho commented on apps/api/src/campaign-application/campaign-application.service.ts
> +    console.log(id)
Remove please

2024-07-26 08:24 UTC, slavcho commented on apps/api/src/campaign-application/campaign-application.service.ts
> +    organaizerId?: string,
typo: organizerId

2024-07-26 08:24 UTC, slavcho commented on apps/api/src/campaign-application/campaign-application.service.ts
> +
Why do we delete the previous files?
I'd say the default is that we incrementally add new files.
If the user wants to delete a file - they should do so explicitly one by one.

2024-07-26 08:24 UTC, slavcho commented on apps/api/src/person/__mock__/personMock.ts
> +  id: 'personId',
why?

2024-07-26 09:21 UTC, Martbul commented on apps/api/src/campaign-application/campaign-application.controller.ts
> +    let isAdminFlag
using person.id

2024-08-07 10:01 UTC, slavcho approved these changes

2024-08-07 19:11 UTC, merged